### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by lavanyakomarasamy** [protobi/js-xlsx#108]
Hi,

Could you help me how to design the header of generated excel?
I have attached the sample image also.
![image](https://user-images.githubusercontent.com/13619132/37651134-273d03e8-2c5d-11e8-9c1d-65428744d68d.png)

**Comment by pietersv** [comment]
Hi @lavanyakomarasamy At a high level, you'll want to set the fill, font, alignment and border for those cells.  For exact code and additional help, contact support@protobi.com and we can write that for you.

**Comment by kamthe** [comment]
Hi @pietersv , i have added the reference to xlsx.full.min.js in my code. do i need to add the reference to xlsx.core.min.js as well? Can you please tell which property name of cell to set for font,border etc?
