### ISSUE TITLE
how to insert image?

### ISSUE THREAD

**Issue by idr17** [protobi/js-xlsx#113]
Hallo all,

Can i insert image ? thanks for advance

**Comment by pietersv** [comment]
@idr17 I believe that's supported in SheetJS Pro, please report back if you're able to license that.

There's also branch that adds this for XLSX format:  https://github.com/xSirrioNx/js-xlsx.  I'm not sure if these additions were made to the underlying source in the `/bits/` directory or made directly to the generated `xlsx.js` file outside of the `make` process.

**Comment by lucasverra** [comment]
Hello @pietersv , the repo you point to in this issue  is not available any more. Does this one https://github.com/protobi/js-xlsx allows me to export a xlsx file with jpg in it ? Cheers !

**Comment by pietersv** [comment]
@lucasverra - 

Images is not in either yet, but is in the commercial SheetJS version.  

This js-xlsx repo is hard for us to invest in maintaining; but we do actively use `https://github.com/protobi/msexcel-builder`, and if this is an important feature for your work, we could implement images in that public project as a billable professional service.  I estimate this would be a day to implement as a feature and add to test cases.  If interested we can move that conversation to support@protobi.com. 

Alternatively if you're interested and available, the lib is open source.  An outline to implement it is:

* Create a simple Excel with an image (e.g. `simple.xlsx`) in an empty directory
* Unzip it (`jar -xvf simple.xlsx`)
* Open it in an IDE (e.g. Webstorm) that can prettify XML
* Look to see how the image is saved, probably
   -- the image itself is in a directory  e.g. `xl/media/image1.png`, that file is mentioned in ...
   -- the image container is described in `xl/drawings/drawing1.png` with a `<Relationship id="rId1"...>` tag, and that id is mentioned in...
   -- the worksheets `xl/worksheets/sheet1.xml` will reference that image in a tag like `<drawing r:id="rId1"/>` and that is tied back to the prior image as...
   -- that relationship is recorded in `/xl/worksheets/_rels/sheet1.xml.rels` in a Relationship tag

Once you see how it works, then it's usually pretty clear how to modify the code to implement it, and we could advise on how to spec the feature and test cases for a PR.
