### ISSUE TITLE
is json_to_sheet supported ?

### ISSUE THREAD

**Issue by BlackSkyJY** [protobi/js-xlsx#115]
Hi, i have a problem, please help me
i see xlsx.utils It doesn't seem to support, could i use SheetJS/js-xlsx json_to_sheet method create a worksheet, and then use protobi/js-xlsx to fill the style?
 thanks

**Comment by MostafaMhmod** [comment]
+1,
I also tried to use the 'json_to_sheet' and the 'table_to_book' methods which whenever i did try to use it the xlsx.utils doesn't seem to have it as a function, so did you find away to get it to work with. json files to export it to a worksheet? @BlackSkyJY

**Comment by BlackSkyJY** [comment]
yes, I have implemented a similar method like 'json_to_sheet',  And use [file-saver] saveAs() method to export it@MostafaMhmod

**Comment by nicewahson** [comment]
Can i get the code?

**Comment by ghost** [comment]
update?
