### ISSUE TITLE
Fix bug when use "read" function with @jandenma/xlsx-style (issue when require jszip)

### ISSUE THREAD

**Issue by ddavid93** [protobi/js-xlsx#138]
The point is I have a workbook written using the original xlsx library ("write" method). When I wanna use the "read" method with `@jandenma/xlsx-style` for make some changes in design, I have the error: "ERROR TypeError: jszip is not a constructor at read_zip (xlsx.js:15531)". I realized what the problem is and fixed temporally in my machine, but it is not a good practice fixing it at nodemodules. I guess there is other users with this problems. In the line 2176 contains `jszip = require('./js' + 'zip').JSZip`, this must to be changed with `jszip = require('./jszip.js')`. If somebody has a better answer please let me know. Thanks

**Comment by JandenMa** [comment]
I am sorry to hear that. But actually because `js-xlsx` makes some issues when i generate one and open by Microsoft Excel App. So I use [ExcelJS](https://github.com/exceljs/exceljs) instead of `js-xlsx` right now. Hope that one can help you.

**Comment by ddavid93** [comment]
Ok, thanks!

Enviado desde Correo para Windows 10

De: Janden Ma
Enviado: sábado, 14 de diciembre de 2019 3:00
Para: protobi/js-xlsx
CC: Daniel David; Manual
Asunto: Re: [protobi/js-xlsx] Fix bug when use "read" function with@jandenma/xlsx-style (issue when require jszip) (#138)

I am sorry to hear that. But actually because js-xlsx makes some issues when i generate one and open by Microsoft Excel App. So I use ExcelJS instead of js-xlsx right now. Hope that one can help you.

**Comment by JandenMa** [comment]
> Ok, thanks! Enviado desde Correo para Windows 10 De: Janden Ma Enviado: sábado, 14 de diciembre de 2019 3:00 Para: protobi/js-xlsx CC: Daniel David; Manual Asunto: Re: [protobi/js-xlsx] Fix bug when use "read" function with@jandenma/xlsx-style (issue when require jszip) (#138) I am sorry to hear that. But actually because js-xlsx makes some issues when i generate one and open by Microsoft Excel App. So I use ExcelJS instead of js-xlsx right now. Hope that one can help you. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No sweat! Good luck!
