### ISSUE TITLE
Fix Documentation For Horizontal Alignment

### ISSUE THREAD

**Issue by esrouter** [protobi/js-xlsx#24]
Great work! Just need to fix docs for the "Cell Styles" section:

```
alignment     vertical         "bottom"||"center"||"top"
            horizontal         "bottom"||"center"||"top"
```

Change to :   
`horizontal 	"left"||"center"||"right"`

Tested changed settings and works.

**Comment by protobi** [comment]
Change made. Also brought in README.md from the beta branch, showing additional format options including page breaks, scale, document properties, etc.

**Comment by esrouter** [comment]
Awesome. I'll look at the new format options!
