### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by knownasilya** [protobi/js-xlsx#4]
Would love some release tags or release on npm (or both).

**Comment by pietersv** [comment]
@knownasilya I may not have gotten the release tags right, tutoring welcome.  

I've published this fork to npm and bower at least until it's merged back in the main project:

* `npm install xlsx-style`
* `bower install js-xlsx-style#beta`

To make this work there are two branches, `master` and `beta`:

* `master` is intended to merge back with `SheetJS/js-xlsx` so I can fetch upstream changes. This does not run make dist and its package.json is the same as the original repo.
* `beta` is what is published to npm and bower. This *does* run make dist so you can use the minified files, and its package.json points to a new project name (js-xlsx-style) and version number.

Any problems with this branch you can report to https://github.com/protobi/js-xlsx/issues.

**Comment by knownasilya** [comment]
Nice!

> I may not have gotten the release tags right, tutoring welcome.

If you have added tags, you can do `git push --tags` to push them to github.

**Comment by krunal1988** [comment]
@pietersv Really awesome stuff with extending styling. 

Two questions i have if you can help me on it:
1) Is is possible to write in already formatted and styled xlsx file ?
2) Is is possible to manage the column width while writing in the file ?

**Comment by azukaar** [comment]
@krunal1988 :
1 - Each cell hold differents attributes, for exemple cell.f is the formulae contained in the cell, whereas cell.s is the style. You are free to modify the content without altering the style.

2 - Most definitly, yes. See this property here : 
![image](https://cloud.githubusercontent.com/assets/7872597/9170929/85ac3678-3f67-11e5-86ea-be07adfb3a07.png)

**Comment by morficus** [comment]
Any plans to publish this to npm?
Since it's a fork from the SheetJS repo, you would need to change some of the info in package.json

**Comment by knownasilya** [comment]
It is, see the second comment above.

**Comment by pietersv** [comment]
Actually it is on npm and bower.  This was noted on https://github.com/SheetJS/js-xlsx/issues/128#issuecomment-111651740 .   I held off adding it to the README.md on this fork so as not to interfere with a pull request back to the main SheetJS/js-xlsx project.  

```
npm install xlsx-style
bower install js-xlsx-style#beta
```
To make this work there are two branches, master and beta:

master is intended to merge back with SheetJS/js-xlsx and until then fetch upstream changes. This does not run make dist and its package.json is the same as the original repo.
beta is what is published to npm and bower. This does run make dist so you can use the minified files, and its package.json points to a new project name (js-xlsx-style) and version number.
Any problems with this branch you can report to https://github.com/protobi/js-xlsx/issues.

**Comment by morficus** [comment]
ah, so it is!
I just read through the comments on that issue.
Thanks :-)
