### ISSUE TITLE
How to force formula recalculation?

### ISSUE THREAD

**Issue by kilpa** [protobi/js-xlsx#48]
Right now when you add formula `=TODAY()` into the xlsx file it will be ran and get cached as the value of the field. When reading the file with js-xlsx the formula is not ran and the value for the cell will be as it was when the file was last opened by a proper application (Excel, Calc etc.).

**Comment by pietersv** [comment]
@kilpa Thank you for reporting. This seems like a major capability.   I recommend adding this as an issue to the root project https://github.com/SheetJS/js-xlsx also. 

In the meantime, I believe it is possible to calculate the expected result independently and cache the result as  a cell value.
