### ISSUE TITLE
In windows, line breaking not work.

### ISSUE THREAD

**Issue by shikelong** [protobi/js-xlsx#73]
I insert \r\n in cell value. But The line breaking only work after I click the edit input or double click the cell.

How to mark line breaking work in windows ?

```javascript

const wbout = XLSX.write(workbook, {bookType: 'xlsx', bookSST: true, type: 'binary'});
  const wblob = new Blob([s2ab(wbout)], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});

```

![gif](https://user-images.githubusercontent.com/4499997/27113724-3cf31c92-50f1-11e7-9691-c4d691145c58.gif)

**Comment by pietersv** [comment]
@shikelong  Good question.  Line breaks would be useful but are not currently implemented in this branch.  Line breaks in Excel are trickier as they are written to the XML not as special characters (e.g; `\n`) but as embedded XML.  But if you enter the XML into the string, the special characters get encoded.   

If urgent, we can create add this as a micro project.  It would likely be 4 billable hours to dev, test and document.  contact support@protobi.com and
