### ISSUE TITLE
how can I set the height for an specific cell?

### ISSUE THREAD

**Issue by jorbope** [protobi/js-xlsx#83]
how can I set the height for an specific cell? for example A1
when I set to that cell a lot of text, I want to see the whole text when I open the xlsx, but currently I have to open the xlsx and resize manually the cell to see the whole text.

**Comment by randomevents** [comment]
It sounds like what you really want is to turn on text wrapping. It's in Cell Styles part of the instructions.

**Comment by jorbope** [comment]
yes, thanks..
I changed the library for another one with a better result for me.

**Comment by randomevents** [comment]
Would you mind sharing which one you ended up going with, I'm trying to review them all for a project I'm working on, even the Pro version of the main (if I can get work to drop the money for it)

**Comment by jorbope** [comment]
ok, here the library
https://www.npmjs.com/package/xlsx-populate

**Comment by duanbowen** [comment]
@randomevents  
hello , do you mind telling me the method of setting the height of the js-xlsx plugin, I see that you mentioned text wrapping, but the documentation states that this is a Boolean value.
